#!/usr/bin/env bash
set -Eeuo pipefail

F2B_DIR="${F2B_DIR:-/etc/fail2ban}"
F2B_JAIL_DIR="${F2B_JAIL_DIR:-$F2B_DIR/jail.d}"
F2B_SSO_LOCAL="${F2B_SSO_LOCAL:-$F2B_JAIL_DIR/sso.local}"
F2B_NGINX_MARKER="${F2B_NGINX_MARKER:-$STATE_DIR/fail2ban-nginx.enabled}"
F2B_AUTH_LOG="${F2B_AUTH_LOG:-/var/log/auth.log}"
F2B_SECURE_LOG="${F2B_SECURE_LOG:-/var/log/secure}"

detect_nginx() {
  command -v nginx >/dev/null 2>&1 || systemctl is-enabled nginx >/dev/null 2>&1
}

ensure_fail2ban_installed() {
  if cmd_exists fail2ban-client; then return 0; fi

  local package_was_installed=0
  if dpkg -s fail2ban >/dev/null 2>&1; then
    package_was_installed=1
  fi

  if ! run_step "Updating package index" apt-get update -y; then
    return 1
  fi
  if ! run_step "Installing Fail2Ban" apt-get install -y fail2ban; then
    return 1
  fi

  if ! dpkg -s fail2ban >/dev/null 2>&1 || ! cmd_exists fail2ban-client; then
    return 1
  fi

  ensure_dirs "$STATE_DIR"
  if [[ "$package_was_installed" == "0" ]]; then
    touch "$STATE_DIR/installed_fail2ban.marker"
  fi
}

fail2ban_collect_whitelist_ips() {
  [[ -f "${STATE_WHITELIST:-}" ]] || return 0
  awk '
    {
      gsub(/\r/, "", $0)
      sub(/[[:space:]]*[#;].*$/, "", $0)
      gsub(/[[:space:]]/, "", $0)
      if ($0 != "") {
        if (printed) printf " "
        printf "%s", $0
        printed=1
      }
    }
  ' "$STATE_WHITELIST"
}

# Debian/Ubuntu minimal images may use journald without creating auth.log.
# Fail2Ban's packaged sshd jail can then be enabled while its default file
# backend has no log file to read. Override only that backend choice when no
# traditional SSH auth log exists and journalctl is available; configuration
# validation remains the final authority on whether the host supports it.
fail2ban_sshd_use_systemd_backend() {
  [[ ! -e "$F2B_AUTH_LOG" && ! -e "$F2B_SECURE_LOG" ]] || return 1
  cmd_exists journalctl
}

fail2ban_render_sso_config() {
  local target="$1"
  local enable_nginx="${2:-0}"
  local ips=""
  ips="$(fail2ban_collect_whitelist_ips)"

  {
    echo "# Managed by Simple Server Optimizer. Do not edit this file manually."
    echo "[DEFAULT]"
    echo "bantime = 1h"
    echo "findtime = 10m"
    echo "maxretry = 5"
    if [[ -n "$ips" ]]; then
      printf 'ignoreip = %s\n' "$ips"
    fi
    echo ""
    echo "[sshd]"
    echo "enabled = true"
    if fail2ban_sshd_use_systemd_backend; then
      echo "backend = systemd"
    fi

    if [[ "$enable_nginx" == "1" ]]; then
      echo ""
      echo "[nginx-http-auth]"
      echo "enabled = true"
    fi
  } > "$target"
}

fail2ban_validate_config() {
  fail2ban-client -t
}

fail2ban_write_managed_config() {
  local enable_nginx="${1:-0}"
  local candidate=""
  local previous=""
  local had_previous=0

  ensure_dirs "$F2B_JAIL_DIR"
  candidate="$(mktemp "$F2B_JAIL_DIR/.sso.local.XXXXXX")"
  chmod 0644 "$candidate"

  if ! fail2ban_render_sso_config "$candidate" "$enable_nginx"; then
    rm -f "$candidate"
    return 1
  fi

  if [[ -f "$F2B_SSO_LOCAL" ]]; then
    had_previous=1
    previous="$(mktemp "$F2B_JAIL_DIR/.sso.previous.XXXXXX")"
    cp -a "$F2B_SSO_LOCAL" "$previous"
  fi

  if ! mv -f "$candidate" "$F2B_SSO_LOCAL"; then
    rm -f "$candidate" "$previous"
    return 1
  fi

  info "Validating Fail2Ban configuration before service changes..."
  if ! fail2ban_validate_config; then
    err "Fail2Ban configuration validation failed. Restoring the previous SSO configuration."
    if [[ "$had_previous" == "1" ]]; then
      cp -a "$previous" "$F2B_SSO_LOCAL"
    else
      rm -f "$F2B_SSO_LOCAL"
    fi
    rm -f "$previous"
    return 1
  fi

  rm -f "$previous"
  return 0
}

fail2ban_apply_service() {
  local service_mode="${1:-preserve}"
  if systemctl is-active --quiet fail2ban 2>/dev/null; then
    run_step "Restarting Fail2Ban" systemctl restart fail2ban
  elif [[ "$service_mode" == "enable" ]]; then
    run_step "Enabling and starting Fail2Ban" systemctl enable --now fail2ban
  else
    info "Fail2Ban service is inactive; leaving its service state unchanged."
  fi
}

fail2ban_apply_managed_config() {
  local enable_nginx="${1:-0}"
  local service_mode="${2:-preserve}"
  fail2ban_write_managed_config "$enable_nginx" || return 1
  fail2ban_apply_service "$service_mode"
}

# Remove only SSO-owned Fail2Ban configuration. Do not stop, disable, enable,
# or uninstall an operator-owned Fail2Ban service as a side effect.
fail2ban_disable_managed_config() {
  local previous="" had_previous=0 marker_was_present=0 was_active=0

  if [[ -e "$F2B_SSO_LOCAL" || -L "$F2B_SSO_LOCAL" ]]; then
    [[ -f "$F2B_SSO_LOCAL" && ! -L "$F2B_SSO_LOCAL" ]] || {
      err "SSO Fail2Ban config is not a normal file; refusing to remove it: $F2B_SSO_LOCAL"
      return 1
    }
    previous="$(mktemp "$F2B_JAIL_DIR/.sso.disable.previous.XXXXXX")" || return 1
    cp -a "$F2B_SSO_LOCAL" "$previous" || { rm -f "$previous"; return 1; }
    had_previous=1
  fi

  [[ -e "$F2B_NGINX_MARKER" || -L "$F2B_NGINX_MARKER" ]] && marker_was_present=1
  systemctl is-active --quiet fail2ban 2>/dev/null && was_active=1

  if ! rm -f -- "$F2B_SSO_LOCAL" "$F2B_NGINX_MARKER"; then
    rm -f "$previous"
    return 1
  fi

  if cmd_exists fail2ban-client; then
    info "Validating remaining Fail2Ban configuration..."
    if ! fail2ban_validate_config; then
      err "Remaining Fail2Ban configuration is invalid; restoring SSO config."
      if [[ "$had_previous" == "1" ]]; then
        cp -a "$previous" "$F2B_SSO_LOCAL" || true
      fi
      if [[ "$marker_was_present" == "1" ]]; then
        : > "$F2B_NGINX_MARKER" 2>/dev/null || true
      fi
      rm -f "$previous"
      return 1
    fi
  elif [[ "$was_active" == "1" ]]; then
    err "Fail2Ban is active but validation tooling is unavailable; SSO config was restored."
    if [[ "$had_previous" == "1" ]]; then
      cp -a "$previous" "$F2B_SSO_LOCAL" || true
    fi
    if [[ "$marker_was_present" == "1" ]]; then
      : > "$F2B_NGINX_MARKER" 2>/dev/null || true
    fi
    rm -f "$previous"
    return 1
  fi

  if [[ "$was_active" == "1" ]]; then
    if ! run_step "Restarting active Fail2Ban without SSO config" systemctl restart fail2ban; then
      err "Fail2Ban restart failed; restoring the previous SSO config."
      if [[ "$had_previous" == "1" ]]; then
        cp -a "$previous" "$F2B_SSO_LOCAL" || true
      fi
      if [[ "$marker_was_present" == "1" ]]; then
        : > "$F2B_NGINX_MARKER" 2>/dev/null || true
      fi
      if cmd_exists fail2ban-client && fail2ban_validate_config >/dev/null 2>&1; then
        systemctl restart fail2ban >/dev/null 2>&1 || true
      fi
      rm -f "$previous"
      return 1
    fi
  else
    info "Fail2Ban service is inactive; leaving its service state unchanged."
  fi

  rm -f "$previous"
  return 0
}

module_fail2ban_install_ssh() {
  header
  section "Fail2Ban: install & enable (SSH)"
  local d
  d="$(backup_create "fail2ban:install_ssh")"

  if ! ensure_fail2ban_installed; then
    err "Failed to install Fail2Ban."
    pause
    return
  fi

  local enable_nginx=0
  [[ -f "$F2B_NGINX_MARKER" ]] && enable_nginx=1

  if ! fail2ban_apply_managed_config "$enable_nginx" enable; then
    err "Fail2Ban configuration was not applied."
    pause
    return
  fi

  ok "Fail2Ban enabled (sshd). SSO config: $F2B_SSO_LOCAL. Backup: $d"
  pause
}

module_fail2ban_enable_nginx() {
  header
  section "Fail2Ban: enable nginx jail"
  local d
  d="$(backup_create "fail2ban:enable_nginx")"

  if ! ensure_fail2ban_installed; then
    err "Fail2Ban not installed."
    pause
    return
  fi

  if ! detect_nginx; then
    warn "nginx not detected. Skipping."
    pause
    return
  fi

  ensure_dirs "$STATE_DIR"
  local marker_was_present=0
  [[ -f "$F2B_NGINX_MARKER" ]] && marker_was_present=1
  : > "$F2B_NGINX_MARKER"

  if ! fail2ban_apply_managed_config 1; then
    if [[ "$marker_was_present" == "0" ]]; then
      rm -f "$F2B_NGINX_MARKER"
    fi
    err "nginx-http-auth jail was not applied."
    pause
    return
  fi

  ok "nginx-http-auth jail enabled via $F2B_SSO_LOCAL. Backup: $d"
  pause
}

module_fail2ban_sync_whitelist() {
  header
  section "Fail2Ban: sync ignoreip from SSO whitelist"
  local d
  d="$(backup_create "fail2ban:sync_whitelist")"

  if ! ensure_fail2ban_installed; then
    err "Fail2Ban not installed."
    pause
    return
  fi

  if ! ensure_default_whitelist; then
    err "SSO whitelist is invalid or unavailable; Fail2Ban was not changed."
    pause
    return
  fi

  local enable_nginx=0
  [[ -f "$F2B_NGINX_MARKER" ]] && enable_nginx=1

  if ! fail2ban_apply_managed_config "$enable_nginx"; then
    err "Whitelist was not applied to Fail2Ban."
    pause
    return
  fi

  ok "Synced ignoreip via $F2B_SSO_LOCAL. Backup: $d"
  pause
}

module_fail2ban_status() {
  header
  section "Fail2Ban status"
  if ! cmd_exists fail2ban-client; then
    warn "Fail2Ban not installed."
    pause
    return
  fi

  info "SSO managed config: $F2B_SSO_LOCAL"
  if cmd_exists systemctl && ! systemctl is-active --quiet fail2ban 2>/dev/null; then
    warn "Fail2Ban service is not running."
    info "systemctl status fail2ban (top lines):"
    systemctl status fail2ban --no-pager -l 2>/dev/null | sed -n '1,60p' || true
    pause
    return
  fi

  info "Fetching Fail2Ban status..."
  if ! fail2ban-client status 2>/dev/null; then
    err "Failed to read Fail2Ban status."
    if cmd_exists journalctl; then
      info "Recent logs (fail2ban):"
      journalctl -u fail2ban -n 20 --no-pager 2>/dev/null || true
    fi
  fi
  pause
}

module_fail2ban_disable() {
  header
  section "Fail2Ban: remove SSO-managed configuration"
  local d
  d="$(backup_create "fail2ban:disable_sso_config")"

  if [[ ! -e "$F2B_SSO_LOCAL" && ! -L "$F2B_SSO_LOCAL" \
    && ! -e "$F2B_NGINX_MARKER" && ! -L "$F2B_NGINX_MARKER" ]]; then
    info "No SSO-managed Fail2Ban configuration is currently present."
    pause
    return 0
  fi

  if ! fail2ban_disable_managed_config; then
    err "SSO Fail2Ban configuration could not be removed safely."
    pause
    return 0
  fi

  ok "SSO Fail2Ban configuration removed; package/service ownership was preserved. (Backup: $d)"
  pause
}

# Compatibility alias for older callers; behavior is now the safe SSO-only
# disable operation instead of stopping the whole Fail2Ban service.
module_fail2ban_rollback() {
  module_fail2ban_disable
}
